### ISSUE TITLE
Google OAuth deleted_client error when trying to read sheet

### ISSUE THREAD

**Issue by MichaelDepner** [Praqma/GSheets2TBoards#23]
It looks like the OAuth client no longer exists. I would guess that it was originally created from a personal account, then later deleted.

Anybody with knowledge of the project is probably better qualified to figure out how to fix this.

This is the error that appears when you visit the link in your browser that the application tells you to. In this case, https://accounts.google.com/o/oauth2/auth?client_id=565384100376-td8kmvmue27mbi2toe0tnup4hpkdgulp.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fspreadsheets.readonly&access_type=offline&response_type=code
```
401. That’s an error.

Error: deleted_client

The OAuth client was deleted.

Request Details
client_id=565384100376-td8kmvmue27mbi2toe0tnup4hpkdgulp.apps.googleusercontent.com
redirect_uri=urn:ietf:wg:oauth:2.0:oob
scope=https://www.googleapis.com/auth/spreadsheets.readonly
access_type=offline
response_type=code
That’s all we know.
```

**Comment by MichaelDepner** [comment]
@sofusalbertsen Do you recognise this, or know anybody who might?

**Comment by sofusalbertsen** [comment]
No, it was @timea who originally created with. I might suspect that due to our move to Eficode, the client tokens have been revoked. But I have no more info than that I'm afraid ...

**Comment by MichaelDepner** [comment]
Issue was resolved by creating a new OAuth app - documentation was added to README.md
